# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a550c306cf90e40d7f9e5ae0217c9728c0733aab19e5b368df741f83599bf5218b59b47dc0acb0a697a9a1113d2a514fd63a8a92a5f96caf3534789cbf9fb949

test:
  secret_key_base: 2e0143ff3b3cf206140cfc237672c3b0895c0c9d6e2a5b59f74f59f26b038239684613c9de188a7ed822dcb240193409bae9e5ffc28e833d23d8cde8e6448d85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
